import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 64;
const MAX_W = PAGE_W - MARGIN * 2;
const PAGES_CAP = 150;
const CHARS_CAP = 400000;

const ACCENT = rgb(0.486, 0.361, 1);
const ACCENT2 = rgb(0.0, 0.72, 0.95);
const DARK = rgb(0.14, 0.14, 0.2);
const MUTED = rgb(0.42, 0.42, 0.52);
const RULE = rgb(0.82, 0.82, 0.9);
const WHITE = rgb(1, 1, 1);

function clean(s) {
  return String(s ?? "").replace(/[^\x20-\x7E\n]/g, "?");
}

function wrap(text, font, size, maxWidth) {
  const words = clean(text).split(/\s+/);
  const lines = [];
  let line = "";
  for (const w of words) {
    const trial = line ? `${line} ${w}` : w;
    if (line && font.widthOfTextAtSize(trial, size) > maxWidth) {
      lines.push(line);
      line = w;
    } else {
      line = trial;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function buildPdf({ title = "Report", subtitle = "", author = "Arynox AI", sections = [], footerText = "Generated by Arynox AI" }) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const list = Array.isArray(sections) ? sections : [];
  let totalChars = 0;
  const content = [];
  for (const s of list) {
    const heading = clean(s?.heading || "");
    const body = String(s?.body ?? "").slice(0, 20000);
    totalChars += heading.length + body.length;
    if (totalChars > CHARS_CAP) break;
    content.push({ heading, body });
  }

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;
  let pageNo = 1;

  const drawFooter = () => {
    const fw = font.widthOfTextAtSize(footerText, 8);
    page.drawText(clean(footerText), { x: MARGIN, y: 36, size: 8, font, color: MUTED });
    const n = String(pageNo);
    page.drawText(n, { x: PAGE_W / 2 - font.widthOfTextAtSize(n, 8) / 2, y: 36, size: 8, font, color: MUTED });
    page.drawText(author, { x: PAGE_W - MARGIN - font.widthOfTextAtSize(clean(author), 8), y: 36, size: 8, font, color: MUTED });
  };

  const needPage = (space) => {
    if (y - space < 90) {
      drawFooter();
      page = doc.addPage([PAGE_W, PAGE_H]);
      pageNo += 1;
      y = PAGE_H - MARGIN;
      if (pageNo > PAGES_CAP) throw new Error(`PDF exceeds ${PAGES_CAP} pages - split it into smaller reports`);
    }
  };

  const drawTitle = () => {
    page.drawRectangle({ x: MARGIN, y: PAGE_H - MARGIN + 10, width: 4, height: 64, color: ACCENT });
    y = PAGE_H - MARGIN + 40;
    const t = clean(title).slice(0, 90);
    const tw = bold.widthOfTextAtSize(t, 22);
    if (tw > MAX_W) {
      for (const line of wrap(t, bold, 22, MAX_W)) {
        page.drawText(line, { x: MARGIN + 16, y, size: 22, font: bold, color: DARK });
        y -= 27;
      }
    } else {
      page.drawText(t, { x: MARGIN + 16, y, size: 22, font: bold, color: DARK });
      y -= 27;
    }
    if (subtitle) {
      const sub = clean(subtitle).slice(0, 200);
      y -= 2;
      for (const line of wrap(sub, font, 11, MAX_W)) {
        page.drawText(line, { x: MARGIN + 16, y, size: 11, font, color: MUTED });
        y -= 15;
      }
    }
    y -= 10;
    const meta = `${clean(author)}   |   ${new Date().toLocaleDateString("en-IN", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`;
    page.drawText(meta.slice(0, 120), { x: MARGIN + 16, y, size: 9, font, color: ACCENT2 });
    y -= 20;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: RULE });
    y -= 30;
  };

  drawTitle();

  for (const sec of content) {
    if (sec.heading) {
      needPage(40);
      page.drawText(sec.heading.slice(0, 120), { x: MARGIN, y, size: 14, font: bold, color: ACCENT });
      y -= 18;
      page.drawLine({ start: { x: MARGIN, y }, end: { x: MARGIN + 60, y }, thickness: 1.5, color: ACCENT });
      y -= 12;
    }
    const bodyLines = String(sec.body).split("\n").flatMap((rawLine) => {
      const line = rawLine.trim();
      if (!line) return [""];
      if (line.startsWith("- ") || line.startsWith("• ")) {
        const txt = line.replace(/^[-•]\s*/, "");
        return wrap(txt, font, 10.5, MAX_W - 14).map((w) => ({ bullet: true, text: w }));
      }
      if (line.startsWith("# ")) return [{ heading: true, text: line.slice(2) }];
      if (line.startsWith("## ")) return [{ sub: true, text: line.slice(3) }];
      return wrap(line, font, 10.5, MAX_W).map((w) => ({ text: w }));
    });
    for (const bl of bodyLines) {
      const lineHeight = bl.heading ? 18 : bl.sub ? 16 : 13;
      needPage(lineHeight);
      if (bl.heading) {
        page.drawText(clean(bl.text).slice(0, 120), { x: MARGIN, y, size: 12, font: bold, color: DARK });
      } else if (bl.sub) {
        page.drawText(clean(bl.text).slice(0, 120), { x: MARGIN, y, size: 11.5, font: bold, color: DARK });
      } else if (bl.bullet) {
        page.drawText("•", { x: MARGIN, y, size: 10.5, font, color: ACCENT });
        page.drawText(clean(bl.text).slice(0, 300), { x: MARGIN + 14, y, size: 10.5, font, color: DARK });
      } else {
        page.drawText(clean(bl.text).slice(0, 300), { x: MARGIN, y, size: 10.5, font, color: DARK });
      }
      y -= lineHeight;
    }
    y -= 6;
  }

  drawFooter();
  const bytes = await doc.save();
  return Buffer.from(bytes);
}
